security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cartong\MSFBundle\Security\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        geonetwork:
            id: webservice_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        msfmapcentre:
            pattern:    ^/
            anonymous: ~
            simple_form:
                login_path: cartong_msf_mapcentre_login
                check_path: cartong_msf_mapcentre_postlogin
                authenticator: geonetwork_authenticator
            logout:
                path:   cartong_msf_mapcentre_logout


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
